### PR TITLE
Instrument teams tool

### PR DESCRIPTION
**Pull request by jwhite3**
IIIIITTTSSSS AAAALLLLIIIIIIVVVVEEEEE

This thing does the following:
1. creates the staging directory on /grp/redcat/staging/
2. moves files 
3. modifies the delivery form to include the new location and names of files being delivered
4. composes and sends an email to redcat

### CODE REVIEW

**Comment by gkanarek** [comment]
Can you use os.chmod that way, without using the specific flags? Or is the permission mode supposed to be a string?

**Comment by jwhite3** [comment]
@gkanarek can you elaborate a little bit?

**Comment by gkanarek** [comment]
Never mind, I tested that line and it works fine. Weird. :)

**Comment by jwhite3** [comment]
Could be weird if you're used to using os.chmod in python 2 vs python 3

I know that for python3 all that's required is the file path and "0o"+ the typical octal code

**Comment by jwhite3** [comment]
And don't worry! I tested this code quite a bit before I initiated a pull request!

**Comment by gkanarek** [comment]
Ha! I forgot that was python for an octal number. Good on ya.

**Comment by jwhite3** [comment]
Any objections if I go ahead and merge this? I've tested it and I think @gkanarek has run it (or parts of it) as well. I want to go ahead and get this out there along with the new documentation so that we can avoid the permission issues

**Comment by gkanarek** [comment]
All I tested was the chmod line. But it all looks pretty good! I'd go ahead and merge it.

**Pull request merged**
